all:myCompiler.g
	java -cp antlr-3.5.3-complete-no-st3.jar org.antlr.Tool myCompiler.g
	javac -cp antlr-3.5.3-complete-no-st3.jar *.java
clean:
	rm -f *class myCompilerLexer.java myCompilerParser.java myCompiler.tokens


